dataset:
  dataset_annotations: /home/hwang6/data/annotations
  dataset_folder: /home/hwang6/data/HaGRIDv2_dataset_512
  phases: [train, val, test] # names of annotation directories
  targets:
    - middle_finger
    - dislike
    - fist
    - four
    - like
    - one
    - palm
    - three
    - two_up
    - no_gesture
    # - grabbing
    # - grip
    # - holy
    # - point
    # - call
    # - three3
    # - timeout
    # - xsign
    # - hand_heart
    # - hand_heart2
    # - little_finger
    # - take_picture
    # - mute
    # - ok
    # - peace
    # - peace_inverted
    # - rock
    # - stop
    # - stop_inverted
    # - three2
    # - two_up_inverted
    # - three_gun
    # - thumb_index
    # - thumb_index2
