dataset:
  dataset_annotations: /home/jovyan/nuzhdin/Hagrid2/HaGRID_V2/HaGRIDv2_annotations_with_meta # Path to annotations
  dataset_folder: /home/jovyan/nuzhdin/Hagrid2/HaGRID_V2/HaGRIDv2_dataset # Path to images
  phases: [train, test, val] #names of annotation directories
  targets:
    - grabbing
    - grip
    - holy
    - point
    - call
    - three3
    - timeout
    - xsign
    - hand_heart
    - hand_heart2
    - little_finger
    - middle_finger
    - take_picture
    - dislike
    - fist
    - four
    - like
    - mute
    - ok
    - one
    - palm
    - peace
    - peace_inverted
    - rock
    - stop
    - stop_inverted
    - three
    - three2
    - two_up
    - two_up_inverted
    - three_gun
    - thumb_index
    - thumb_index2
    - no_gesture
